version: '3'
services:
  ips-app:
    build:
      context: .
    restart: always
    image: ips-app:v1.0
    # command: ["sh", "-c", "sleep 3"]
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/ips
    depends_on:
      - postgresql
    networks:
        - mynetwork


  postgresql:
    image: postgres
    restart: always
    user: postgres
    # command: ["sh", "-c", "echo POSTGRES_PASSWORD: $POSTGRES_PASSWORD"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ips
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork



networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

